<?php


namespace iTzFreeHD\cServerList\gui;


use formBridge\form\CustomForm;
use formBridge\form\element\Input;
use formBridge\form\Form;
use iTzFreeHD\cServerList\ConsoleServerList;
use pocketmine\Player;

class ServerEditGui extends CustomForm
{

    /** @var int */
    private $id;

    public function __construct(int $id = -1, string $name = "Minecraft Server", string $ip = "", int $port = 19132)
    {
        $this->id = $id;
        parent::__construct("Add/edit server", [
            new Input("Server name", "", $name),
            new Input("Ip", "", $ip),
            new Input("Port", "", $port),
        ]);
    }

    public function onSubmit(Player $player): ?Form
    {
        $name = $this->getElement(0);
        $ip = $this->getElement(1);
        $port = $this->getElement(2);
        if ($this->id == -1) {
            ConsoleServerList::getInstance()->getServerConfig()->addServer($name->getValue(), $ip->getValue(), intval($port->getValue()));
            ConsoleServerList::getInstance()->openGui($player);
            return null;
        }
        ConsoleServerList::getInstance()->getServerConfig()->editServer($this->id, $name->getValue(), $ip->getValue(), intval($port->getValue()));
        ConsoleServerList::getInstance()->openGui($player);
        return parent::onSubmit($player);
    }

    public function onClose(Player $player): ?Form
    {
        ConsoleServerList::getInstance()->openGui($player);
        return parent::onClose($player); // TODO: Change the autogenerated stub
    }

}