<?php


namespace iTzFreeHD\cServerList\gui;


use formBridge\form\Form;
use formBridge\form\MenuForm;
use formBridge\form\MenuOption;
use iTzFreeHD\cServerList\ConsoleServerList;
use pocketmine\Player;
use pocketmine\utils\TextFormat as c;

class ServerListGui extends MenuForm
{

    private $serverList;

    public function __construct(array $serverList)
    {
        $this->serverList = $serverList;
        $options = [];
        foreach (ConsoleServerList::getInstance()->getServerConfig()->getServerList() as $key => $serverInfo) {
            $values = $serverList[$key];
            if ($values["HostName"] == null) {
                $options[] = new MenuOption($serverInfo["name"]."\n".c::RED."Out of reach!");
                continue;
            }
            $options[] = new MenuOption($serverInfo["name"]."\n".$values["HostName"].c::GRAY." -> ".c::YELLOW.$values["Players"].c::DARK_GRAY."/".c::YELLOW.$values["MaxPlayers"]);
        }
        $options[] = new MenuOption("Add server");
        parent::__construct("Minecraft Server List", "Coded by iTzFreeHD", $options);
    }

    public function onClose(Player $player): ?Form
    {
        ConsoleServerList::getInstance()->openGui($player);
        return parent::onClose($player); // TODO: Change the autogenerated stub
    }

    public function onSubmit(Player $player): ?Form
    {
        if (!isset($this->serverList[$this->getSelectedOptionIndex()])) {
            $player->sendForm(new ServerEditGui());
            return null;
        }
        $player->sendForm(new ServerSingleGui($this->getSelectedOptionIndex(), $this->serverList[$this->getSelectedOptionIndex()]));
        return parent::onSubmit($player); // TODO: Change the autogenerated stub
    }

}